
name: CI
on: [push, pull_request, workflow_dispatch]

jobs:
  ## Check for trailing white space, line width, tabs, etc.
  style-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run static checks.
        run: |
          python3 scripts/static_check.py
  
  ## Compile and run test on linux.
  linux-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run the Makefile.
        run: |
          make all
      - name: Run tests.
        run: |
          python3 scripts/run_tests.py

  ## Compile and run tests on windows.
  windows-build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2      
      - name: Run build batch script.
        run: |
          cmd /c scripts\build.bat
      - name: Run tests.
        run: |
          python3 scripts/run_tests.py

  ## Compile and run tests on macos.
  macos-build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run the Makefile.
        run: |
          make all
      - name: Run tests.
        run: |
          python3 scripts/run_tests.py


